### ISSUE TITLE
Upgrade to Angular 5

### ISSUE THREAD

**Issue by tidusjar** [MattJeanes/AngularBasic#4]
We should upgrade this to use Angular 5 now

**Comment by AmyJeanes** [comment]
Awaiting teradata/covalent to support material 5.0-rc1

**Comment by AmyJeanes** [comment]
https://github.com/Teradata/covalent/pull/967

**Comment by AmyJeanes** [comment]
Done in https://github.com/MattJeanes/AngularBasic/commit/35cddb727b8bc8a95285111bd29ed314dfe40d74
